import json
import os
import sys
import subprocess
import pandas as pd

from utils.outputs_config import save_file

from codecarbon import EmissionsTracker
from measurements.base_energy_meter import BaseEnergyMeter
from tempfile import TemporaryDirectory

class CodeCarbonEnergyMeter(BaseEnergyMeter):
    def __init__(self, file_path, logger):
        """
        Initializes the CodeCarbonEnergyMeter with a file path and logger.
        
        :param file_path: Path to the file to measure energy consumption.
        :param logger: Logger instance for logging events.
        """
        super().__init__(file_path, logger)
        self.emissions_data = None

    def measure_energy(self):
        """
        Measures the carbon emissions for the specified file by running it with CodeCarbon.
        Logs each step and stores the emissions data if available.
        """
        if not self.validate_file():
            return

        self.logger.log(f"Starting CodeCarbon energy measurement on {os.path.basename(self.file_path)}")

        with TemporaryDirectory() as custom_temp_dir:
            os.environ['TEMP'] = custom_temp_dir  # For Windows
            os.environ['TMPDIR'] = custom_temp_dir  # For Unix-based systems

            # TODO: Save to logger so doesn't print to console
            tracker = EmissionsTracker(output_dir=custom_temp_dir, allow_multiple_runs=True)
            tracker.start()

            try:
                subprocess.run([sys.executable, self.file_path], capture_output=True, text=True, check=True)
                self.logger.log("CodeCarbon measurement completed successfully.")
            except subprocess.CalledProcessError as e:
                self.logger.log(f"Error executing file '{self.file_path}': {e}")
            finally:
                self.emissions = tracker.stop()
                emissions_file = os.path.join(custom_temp_dir, "emissions.csv")

                if os.path.exists(emissions_file):
                    self.emissions_data = self.extract_emissions_csv(emissions_file)
                else:
                    self.logger.log("Emissions file was not created due to an error during execution.")
                    self.emissions_data = None

    def extract_emissions_csv(self, csv_file_path):
        """
        Extracts emissions data from a CSV file generated by CodeCarbon.
        
        :param csv_file_path: Path to the CSV file.
        :return: Dictionary containing the last row of emissions data or None if an error occurs.
        """
        if os.path.exists(csv_file_path):
            try:
                df = pd.read_csv(csv_file_path)
                return df.to_dict(orient="records")[-1]
            except Exception as e:
                self.logger.log(f"Error reading file '{csv_file_path}': {e}")
                return None
        else:
            self.logger.log(f"File '{csv_file_path}' does not exist.")
            return None
