import logging
import os
from pathlib import Path
import sys
import subprocess
import pandas as pd
from tempfile import TemporaryDirectory
from codecarbon import EmissionsTracker

from .base_energy_meter import BaseEnergyMeter

# Configure logger for measurements
logger = logging.getLogger("measurements")


class CodeCarbonEnergyMeter(BaseEnergyMeter):
    """
    Measures energy consumption using the CodeCarbon library.
    """

    def __init__(self):
        """
        Initializes the CodeCarbonEnergyMeter.
        """
        super().__init__()
        self.emissions_data = None

    def measure_energy(self, file_path: Path):
        """
        Measures the carbon emissions for the specified file by executing it within CodeCarbon tracking.

        Args:
            file_path (Path): Path to the Python file to measure energy consumption.
        """
        logger.info("=" * 100)
        logger.info(f"Starting CodeCarbon energy measurement on {file_path}")

        with TemporaryDirectory() as custom_temp_dir:
            os.environ["TEMP"] = custom_temp_dir  # For Windows
            os.environ["TMPDIR"] = custom_temp_dir  # For Unix-based systems

            tracker = EmissionsTracker(
                output_dir=custom_temp_dir,
                allow_multiple_runs=True,
                tracking_mode="process",
                log_level="error",
            )  # type: ignore

            tracker.start()

            try:
                subprocess.run(
                    [sys.executable, file_path], capture_output=True, text=True, check=True
                )
            except subprocess.CalledProcessError as e:
                logger.error(f"Error executing file '{file_path}': {e}")
            finally:
                self.emissions = tracker.stop()
                emissions_file = Path(custom_temp_dir) / "emissions.csv"

                if emissions_file.exists():
                    self.emissions_data = self.extract_emissions_csv(emissions_file)
                else:
                    logger.warning(
                        "Emissions file was not created due to an error during execution."
                    )
                    self.emissions_data = None

                logger.info(
                    f"CodeCarbon measurement completed successfully. Emissions = {self.emissions}"
                )
                logger.info("=" * 100 + "\n")

    def extract_emissions_csv(self, csv_file_path: Path):
        """
        Extracts emissions data from a CSV file generated by CodeCarbon.

        Args:
            csv_file_path (Path): Path to the CSV file.

        Returns:
            dict: The last row of emissions data as a dictionary, or None if an error occurs.
        """
        if csv_file_path.exists():
            try:
                df = pd.read_csv(csv_file_path)
                return df.to_dict(orient="records")[-1]
            except Exception as e:
                logger.error(f"Error reading file '{csv_file_path}': {e}")
                return None
        else:
            logger.warning(f"File '{csv_file_path}' does not exist.")
            return None
