name: "Lint Python Files"

on:
    pull_request:
      types: [opened, reopened, synchronize]
      branches: [dev]
      paths:
        - "src/**/*.py"
  
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Create app access token
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ vars.SCO_COMMIT_APP }}
                private-key: ${{ secrets.SCO_APP_KEY }}

            # Checkout repository
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}

            - name: Run Ruff
              uses: astral-sh/ruff-action@v1
              with:
                args: "--config pyproject.toml"
                changed-files: "true"
            
